import { NextResponse } from "next/server";
import { nanoid } from "nanoid";
import { generateSow } from "@/lib/mistral";
import { saveProject } from "@/lib/redis";
import { Project } from "@/lib/types";

export async function POST(request: Request) {
  try {
    const { freelancerName, clientNotes, basePrice, raenestLink } =
      await request.json();

    if (!freelancerName || !clientNotes || !basePrice || !raenestLink) {
      return NextResponse.json(
        { error: "All fields are required" },
        { status: 400 }
      );
    }

    const sowData = await generateSow(clientNotes, basePrice);
    const projectId = nanoid(12);

    const project: Project = {
      projectId,
      status: "DRAFT",
      createdAt: new Date().toISOString(),
      freelancerName,
      raenestLink,
      freelancerUrl: `/project/${projectId}`,
      clientUrl: `/portal/${projectId}`,
      sowData,
      activityLog: [
        {
          id: nanoid(8),
          date: new Date().toISOString(),
          type: "SYSTEM",
          message: "Project created. SOW generated by AI.",
          scopeVerdict: null,
          reviewStatus: null,
          surcharge: null,
          aiReasoning: null,
        },
      ],
    };

    await saveProject(project);

    return NextResponse.json(project);
  } catch (error) {
    console.error("Generate SOW error:", error);
    return NextResponse.json(
      { error: "Failed to generate SOW" },
      { status: 500 }
    );
  }
}
